service: cas-agd-tlmdcn-availability
useDotenv: true

plugins:
  - "@nearst/serverless-dynalite"
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    SERVICE_NAME: ${self:service}
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-table
  apiGateway:
    restApiId: ${self:custom.cas-agd-tlmdcn.ApiGatewayRestApiId}
    restApiRootResourceId: ${self:custom.cas-agd-tlmdcn.ApiGatewayRestApiRootResourceId}
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: "*"

custom:
  cas-agd-tlmdcn:
    ApiGatewayRestApiId:
      "Fn::ImportValue": cas-agd-tlmdcn-${sls:stage}-ApiGatewayRestApiId
    ApiGatewayRestApiRootResourceId:
      "Fn::ImportValue": cas-agd-tlmdcn-${sls:stage}-ApiGatewayRestApiRootResourceId
  cas-medicap:
    EventBusName:
      "Fn::ImportValue": cas-medicap-${sls:stage}-EventBusName

functions:
  httpAvailabilityGet:
    handler: ./src/application/functions/http-availability-get.handler
    events:
      - http:
          path: /availability
          method: get
          cors: true

  eventMedicapBookingSynced:
    handler: ./src/application/functions/event-medicap-booking-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - booking-synced

  eventMedicapPreBookingSynced:
    handler: ./src/application/functions/event-medicap-pre-booking-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - pre-booking-synced

  eventMedicapReleaseSynced:
    handler: ./src/application/functions/event-medicap-release-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - release-synced

  eventMedicapCalendarSynced:
    handler: ./src/application/functions/event-medicap-calendar-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - calendar-synced

  eventMedicapExceptionSynced:
    handler: ./src/application/functions/event-medicap-exception-synced.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.cas-medicap.EventBusName}
          pattern:
            source:
              - cas-medicap-sync
            detail-type:
              - exception-synced

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: _pk
            AttributeType: S
          - AttributeName: _sk
            AttributeType: S
          - AttributeName: _gsi1pk
            AttributeType: S
          - AttributeName: _gsi1sk
            AttributeType: S
        KeySchema:
          - AttributeName: _pk
            KeyType: HASH
          - AttributeName: _sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: _gsi1pk
                KeyType: HASH
              - AttributeName: _gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
